# .github/workflows/reusable-workflow.yml
name: branch default workflow

on:
  workflow_call:
    inputs:
      exchange_name:
        description: "exchange-name of repo to transfer"
        required: true
        type: string

jobs:
  build:
    if: (contains(github.event.head_commit.message, 'build') && !contains(github.event.head_commit.message, 'skip ci'))
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Pushes to another repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add prod https://x-access-token:${{ secrets.API_TOKEN_FOR_CCXT_SINGLE_EXCHANGES }}@github.com/ccxt/python-${{ inputs.exchange_name }}.git
          git pull prod
          git push prod