# .github/workflows/reusable-workflow.yml
name: branch default workflow

on:
  workflow_call:
    inputs:
      exchange_name:
        description: "exchange-name of repo to transfer"
        required: true
        type: string

jobs:
  build:
    if: (contains(github.event.head_commit.message, 'build') && !contains(github.event.head_commit.message, 'skip ci'))
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: push to remote
        run: |
          git remote remove origin || true
          git credential reject
          git config --global user.name "ttodua"
          git config --global user.email "ccxt_githubactions@github.com"
          git remote add prod https://ttodua:${{ secrets.API_TOKEN_FOR_CCXT_SINGLE_EXCHANGES }}@github.com/ccxt/python-${{inputs.exchange_name}}.git
          git push prod main