# .github/workflows/reusable-workflow.yml
name: branch default workflow

on:
  workflow_call:
    inputs:
      exchange_name:
        description: "exchange-name of repo to transfer"
        required: true
        type: string

jobs:
  build:
    if: (contains(github.event.head_commit.message, 'build') && !contains(github.event.head_commit.message, 'skip ci'))
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Pushes to another repository
        run: |
          git config user.name ttodua
          git config user.email 7117978+ttodua@users.noreply.github.com
          git remote add prod https://ttodua:${{ secrets.API_TOKEN_FOR_CCXT_SINGLE_EXCHANGES }}@github.com/ccxt/python-${{inputs.exchange_name}}.git
          git push prod