name: build
on:
  push:
    branches:
      - main

jobs:
  use-reusable-workflow:
    strategy:
      matrix:
        exchange_name: [kucoin] # ['binance', 'bingx', 'bitget', 'bitmart', 'bitmex', 'bybit', 'coinex', 'cryptocom', 'gate', 'hashkey', 'htx', 'hyperliquid', 'kucoin', 'kucoinfutures', 'mexc', 'okx', 'woo', 'woofipro']
    uses: ./.github/workflows/transfer-exchange.yml
    with:
      exchange_name: ${{ matrix.exchange_name }}
    secrets: inherit