name: build
on:
  push:
    branches:
      - main

jobs:
  transfer-step:
    strategy:
      matrix:
        exchange_name: ['htx',  'woo' ]
    uses: ./.github/workflows/transfer-exchange.yml
    with:
      exchange_name: ${{ matrix.exchange_name }}
    secrets: inherit