
name: branch default workflow

on:
  workflow_call:
    inputs:
      exchange_name:
        description: "exchange-name of repo to transfer"
        required: true
        type: string

jobs:
  distribute_job:
    if: contains(github.event.head_commit.message, '[TRANSFER]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Push to another repo
        run: |
          chmod +x .github/scripts/push-to-repo.sh
          .github/scripts/push-to-repo.sh "${{ inputs.exchange_name }}" "${{ github.event.head_commit.message }}"
        env:
          GITHUB_API_TOKEN: ${{ secrets.API_TOKEN_FOR_CCXT_SINGLE_EXCHANGES }}
  
      ##### APPROACH 2 #####
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git remote add prod https://x-access-token:${{ secrets.API_TOKEN_FOR_CCXT_SINGLE_EXCHANGES }}@github.com/ccxt/python-${{ inputs.exchange_name }}.git
      #     git config pull.rebase false
      #     git fetch --unshallow origin
      #     git pull --allow-unrelated-histories prod main || echo "Git pull failed"
      #     git push prod main --force
